plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("com.google.devtools.ksp")
    id("org.jetbrains.kotlin.plugin.compose")
}

android {
    namespace   = "com.edgetutor"
    compileSdk  = 35

    defaultConfig {
        applicationId = "com.edgetutor.mlc"
        minSdk        = 26          // MLC-LLM requires Android 8.0+
        targetSdk     = 33
        versionCode   = 1
        versionName   = "0.1.0-mlc"

        // MLC-LLM only ships arm64 native libraries
        ndk { abiFilters.add("arm64-v8a") }
    }

    buildFeatures { compose = true }

    kotlinOptions { jvmTarget = "17" }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    packaging {
        resources.excludes += setOf("META-INF/AL2.0", "META-INF/LGPL2.1")
    }

    lint {
        checkReleaseBuilds = false
    }
}

dependencies {
    // MLC-LLM Android runtime — generated by `mlc_llm package`
    // Provides MLCEngine + libtvm4j_runtime_packed.so (OpenCL GPU path)
    implementation(project(":mlc4j"))

    // Jetpack Compose BOM
    val composeBom = platform("androidx.compose:compose-bom:2024.09.00")
    implementation(composeBom)
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.activity:activity-compose:1.9.0")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.0")

    // Room — metadata DB for document list
    val roomVersion = "2.7.0"
    implementation("androidx.room:room-runtime:$roomVersion")
    implementation("androidx.room:room-ktx:$roomVersion")
    ksp("androidx.room:room-compiler:$roomVersion")

    // ONNX Runtime Mobile — embedding model inference (arctic.onnx)
    implementation("com.microsoft.onnxruntime:onnxruntime-android:1.22.0")

    // PDF parsing — on-device text extraction
    implementation("com.tom-roush:pdfbox-android:2.0.27.0")

    // Material Components — Theme.EdgeTutor XML theme
    implementation("com.google.android.material:material:1.12.0")

    // Coroutines
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.0")

    // Gson — FlatIndex JSON serialisation
    implementation("com.google.code.gson:gson:2.10.1")
}
