package com.edgetutor.llm

import android.content.Context
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.coroutines.withContext
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException

/**
 * LLM engine backed by MLC-LLM (GPU/OpenCL path via TVM runtime).
 *
 * Model: Qwen2.5-0.5B-Instruct-q4f16_0  (~300-400 MB, bundled via mlc_llm package)
 *
 * PRE-REQUISITES before building:
 *   1. Run `mlc_llm package` from the android-mlc/ directory — this generates
 *      dist/lib/mlc4j/ (the :mlc4j Gradle subproject) and bundles model weights
 *      into app/src/main/assets/.
 *   2. NDK 27.0.11718014+ and env vars must be set — see android-mlc/README.md.
 *
 * DEVICE REQUIREMENT: physical ARM64 device with OpenCL-capable GPU (Adreno preferred).
 * Cannot run in the Android emulator.
 *
 * IMPORTANT — quantization variant:
 *   Use q4f16_0 (NOT q4f16_1 / q4f32_1). The "_1" variants cause Adreno GPU
 *   system-UI freezes on Snapdragon 855/865/870/888 devices.
 *
 * API NOTE:
 *   The exact MLCEngine constructor and streaming method are defined inside the
 *   generated mlc4j subproject. Verify against:
 *     dist/lib/mlc4j/src/main/java/ai/mlc/mlcengine/MLCEngine.java  (after mlc_llm package)
 *   and the reference app:
 *     https://github.com/mlc-ai/mlc-llm/tree/main/android/MLCChat
 */
class MlcEngine(private val context: Context) : LlmEngine {

    // Loaded lazily on first warmUp() call.
    // Type is Any? to avoid a compile-time hard dependency on mlc4j before it's generated.
    // Replace with `MLCEngine?` once mlc4j is available after running `mlc_llm package`.
    private var engine: Any? = null

    override suspend fun copyModelIfNeeded() = Unit  // weights are bundled by mlc_llm package

    /**
     * Initialises the MLCEngine and loads model weights into GPU memory.
     * Expect 10-30 seconds on first call (CPU→GPU weight transfer).
     * Subsequent calls within the same process are instant.
     */
    override suspend fun warmUp() = withContext(Dispatchers.IO) {
        if (engine != null) return@withContext
        // TODO: replace the reflection-based call below with a direct constructor call
        //       once dist/lib/mlc4j is generated by `mlc_llm package`.
        //
        // Direct call (after mlc4j is generated):
        //   engine = ai.mlc.mlcengine.MLCEngine(context, MODEL_ID)
        //
        // The constructor signature may vary — check the generated MLCEngine sources.
        try {
            val clazz = Class.forName("ai.mlc.mlcengine.MLCEngine")
            engine = clazz
                .getConstructor(Context::class.java, String::class.java)
                .newInstance(context, MODEL_ID)
        } catch (e: ClassNotFoundException) {
            throw IllegalStateException(
                "MLCEngine not found. Run `mlc_llm package` from android-mlc/ first " +
                "to generate the mlc4j Gradle subproject.", e
            )
        }
    }

    /**
     * Streams a response token-by-token, calling [onToken] for each delta.
     * Returns the full response string.
     *
     * Stop sequences are applied post-hoc as MLC-LLM handles them internally via
     * the model's chat config, but we apply our own safety net as well.
     */
    override suspend fun generate(prompt: String, onToken: (String) -> Unit): String =
        withContext(Dispatchers.IO) {
            val eng = engine ?: error("MlcEngine not warmed up — call warmUp() first")

            // TODO: replace the reflection-based call below with a direct method call
            //       once dist/lib/mlc4j is generated by `mlc_llm package`.
            //
            // Direct call (after mlc4j is generated):
            //   val sb = StringBuilder()
            //   eng.generate(buildChatPrompt(prompt)) { delta: String ->
            //       val stop = stopAt(sb, delta)
            //       if (stop != null) return@generate stop
            //       onToken(delta)
            //   }
            //   sb.toString()
            //
            // The streaming callback signature may vary — check MLCChat's AppViewModel.kt.

            suspendCancellableCoroutine { cont ->
                try {
                    val generateMethod = eng.javaClass.getMethod("generate", String::class.java, Function1::class.java)
                    val sb = StringBuilder()
                    var stopped = false
                    generateMethod.invoke(eng, buildChatPrompt(prompt)) { delta: Any? ->
                        if (stopped || delta == null) return@invoke
                        val token = delta.toString()
                        val stop = stopAt(sb, token)
                        if (stop != null) {
                            stopped = true
                            val newPart = stop.drop(sb.length - token.length)
                            if (newPart.isNotEmpty()) onToken(newPart)
                            cont.resume(stop)
                        } else {
                            onToken(token)
                        }
                    }
                    if (!stopped) cont.resume(sb.toString())
                } catch (e: Exception) {
                    cont.resumeWithException(e)
                }
            }
        }

    override fun close() {
        try {
            engine?.javaClass?.getMethod("close")?.invoke(engine)
        } catch (_: Exception) {}
        engine = null
    }

    private fun buildChatPrompt(userContent: String): String =
        "<|im_start|>system\n$SYSTEM_PROMPT<|im_end|>\n" +
        "<|im_start|>user\n$userContent<|im_end|>\n" +
        "<|im_start|>assistant\n"

    /** Accumulates [delta] into [sb]; returns trimmed response if a stop sequence is found. */
    private fun stopAt(sb: StringBuilder, delta: String): String? {
        sb.append(delta)
        val idx = STOP_SEQUENCES
            .mapNotNull { seq -> sb.indexOf(seq).takeIf { it >= 0 } }
            .minOrNull()
        return if (idx != null) sb.substring(0, idx) else null
    }

    companion object {
        private const val MODEL_ID      = "Qwen2.5-0.5B-Instruct-q4f16_0"
        private const val SYSTEM_PROMPT = "Be concise."
        private val STOP_SEQUENCES = listOf(
            "<|im_end|>",
            "<|im_start|>",
            "<|endoftext|>",
            "\nHuman:", "\nUser:", "\nQuestion:", "\nAssistant:",
        )
    }
}
