pluginManagement {
    repositories {
        google(); mavenCentral(); gradlePluginPortal()
    }
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories { google(); mavenCentral() }
}
rootProject.name = "EdgeTutorMlc"
include(":app")

// mlc4j is generated by `mlc_llm package` — run that command first.
// See android-mlc/README.md for full setup instructions.
include(":mlc4j")
project(":mlc4j").projectDir = file("dist/lib/mlc4j")